language: ruby
git:
  depth: 999
before_script:
- export RAILS_ENV=development
- export GITHUB_SLUG=${TRAVIS_REPO_SLUG}
- export PULL_REQUEST_ID=${TRAVIS_PULL_REQUEST}
- export PRONTO_FORMATTER=$([ "${GITHUB_ACCESS_TOKEN}" != "" ] && echo 'github_pr' || echo 'text')
script:
- bundle exec pronto run -f ${PRONTO_FORMATTER} -c ${TRAVIS_BRANCH}
- bundle exec rake test
rvm:
- 2.0.0
- 1.9.3
